# Generated by Django 4.0 on 2022-04-15 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.CharField(max_length=200)),
                ('indus_slug', models.SlugField(max_length=150)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'TechIndustries',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='TechList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alphabet', models.CharField(max_length=4)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'TechLists',
                'ordering': ('alphabet',),
            },
        ),
        migrations.CreateModel(
            name='TechCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('comp_slug', models.SlugField(max_length=150)),
                ('founders', models.CharField(max_length=200)),
                ('twitter_handle', models.CharField(max_length=100)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comp_alphabet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alpha', to='industry.techlist')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indus', to='industry.techindustry')),
            ],
            options={
                'verbose_name_plural': 'TechCompanies',
                'ordering': ('-updated',),
            },
        ),
    ]
