# Generated by Django 4.0 on 2022-04-15 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='techcompany',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
